#!/usr/bin/env python3
"""
terminal-server.py

WebSocket PTY bridge. Spawns real PTY sessions via Python's stdlib `pty` module.
Zero pip dependencies on macOS/Linux. Each session persists across WebSocket
reconnects (e.g. modal close/reopen) — Neovim stays alive.

Protocol (all messages are JSON):
  Client -> Server:
    { "type": "spawn",  "sessionId": str, "cols": int, "rows": int, "cwd": str }
    { "type": "attach", "sessionId": str }
    { "type": "input",  "sessionId": str, "data": str }
    { "type": "resize", "sessionId": str, "cols": int, "rows": int }
    { "type": "kill",   "sessionId": str }
    { "type": "ping" }

  Server -> Client:
    { "type": "ready" }
    { "type": "output", "data": str }
    { "type": "exit",   "code": int }
    { "type": "error",  "message": str }
"""

import asyncio
import fcntl
import json
import os
import pty
import signal
import struct
import sys
import termios
import threading
import urllib.parse  # Used for parsing the security token query parameter

# ── Dependency check: websockets ────────────────────────────────────────────
try:
    import websockets
    from websockets.server import serve
except ImportError:
    print("[terminal-server] ERROR: 'websockets' package not found.", flush=True)
    print("[terminal-server] Install it with: pip3 install websockets", flush=True)
    sys.exit(1)

PORT = 7703
HOST = "127.0.0.1"

# Read the expected security token generated by the plugin
EXPECTED_TOKEN = os.environ.get("TERMINAL_SERVER_TOKEN", "")

# sessions: { sessionId -> { "master_fd": int, "pid": int, "clients": set, "output_buf": list } }
sessions = {}
sessions_lock = threading.Lock()

# asyncio event loop (set once on startup)
loop: asyncio.AbstractEventLoop = None


# ── PTY helpers ──────────────────────────────────────────────────────────────

def set_pty_size(master_fd: int, cols: int, rows: int):
    """Resize the PTY window via ioctl."""
    if cols <= 0 or rows <= 0:
        return
    try:
        size = struct.pack("HHHH", rows, cols, 0, 0)
        fcntl.ioctl(master_fd, termios.TIOCSWINSZ, size)
    except Exception:
        pass


def spawn_pty(cwd: str, cols: int, rows: int):
    """Fork a login shell into a new PTY. Returns (pid, master_fd)."""
    shell = os.environ.get("SHELL", "/bin/zsh")
    env = {
        **os.environ,
        "TERM": "xterm-256color",
        "COLORTERM": "truecolor",
        "LANG": "en_US.UTF-8",
        "LC_ALL": "en_US.UTF-8",
    }

    pid, master_fd = pty.fork()

    if pid == 0:
        # Child process — exec the shell
        if cwd and os.path.isdir(cwd):
            os.chdir(cwd)
        os.execvpe(shell, [shell, "-l"], env)
        sys.exit(1)  # unreachable

    # Parent — set initial terminal size
    set_pty_size(master_fd, cols, rows)
    return pid, master_fd


def read_pty_thread(session_id: str):
    """
    Background thread: reads output from the PTY master_fd and
    schedules broadcast coroutines onto the asyncio event loop.
    Runs until the child exits or the fd is closed.
    """
    with sessions_lock:
        session = sessions.get(session_id)
    if not session:
        return

    master_fd = session["master_fd"]

    while True:
        try:
            data = os.read(master_fd, 4096)
            if not data:
                break
        except OSError:
            # PTY closed (child exited)
            break

        text = data.decode("utf-8", errors="replace")
        asyncio.run_coroutine_threadsafe(
            broadcast(session_id, {"type": "output", "data": text}),
            loop,
        )

    # Child exited — reap it
    with sessions_lock:
        session = sessions.get(session_id)
    if session:
        pid = session["pid"]
        exit_code = 0
        try:
            _, status = os.waitpid(pid, 0)
            exit_code = os.waitstatus_to_exitcode(status)
        except ChildProcessError:
            pass
        try:
            os.close(master_fd)
        except OSError:
            pass
        with sessions_lock:
            sessions.pop(session_id, None)

        asyncio.run_coroutine_threadsafe(
            broadcast(session_id, {"type": "exit", "code": exit_code}),
            loop,
        )


# ── WebSocket helpers ────────────────────────────────────────────────────────

async def broadcast(session_id: str, msg: dict):
    """Send a message to all clients subscribed to a session."""
    with sessions_lock:
        session = sessions.get(session_id)
    if not session:
        return
    text = json.dumps(msg)
    dead = set()
    for ws in list(session["clients"]):
        try:
            await ws.send(text)
        except Exception:
            dead.add(ws)
    if dead:
        with sessions_lock:
            if session_id in sessions:
                sessions[session_id]["clients"] -= dead


async def send(ws, msg: dict):
    try:
        await ws.send(json.dumps(msg))
    except Exception:
        pass


# ── Connection handler ───────────────────────────────────────────────────────

async def handle(ws):
    # Retrieve and validate the security token from query parameters
    try:
        query = urllib.parse.urlparse(ws.path).query
        params = urllib.parse.parse_qs(query)
        client_token = params.get("token", [None])[0]
    except Exception:
        client_token = None

    # Reject immediately if the token is incorrect or missing
    if not EXPECTED_TOKEN or client_token != EXPECTED_TOKEN:
        try:
            await ws.close(code=1008, reason="Unauthorized")
        except Exception:
            pass
        return

    current_session_id = None

    try:
        async for raw in ws:
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                continue

            t = msg.get("type")
            session_id = msg.get("sessionId")

            if t == "ping":
                await send(ws, {"type": "ready"})

            elif t == "spawn":
                # Kill existing session if reusing the same id
                if session_id in sessions:
                    destroy_session(session_id)

                cols = int(msg.get("cols", 80))
                rows = int(msg.get("rows", 24))
                
                # Prevent invalid or zero sizing during spawn
                if cols <= 0:
                    cols = 80
                if rows <= 0:
                    rows = 24

                cwd  = msg.get("cwd", os.path.expanduser("~"))

                try:
                    pid, master_fd = spawn_pty(cwd, cols, rows)
                except Exception as e:
                    await send(ws, {"type": "error", "message": str(e)})
                    continue

                with sessions_lock:
                    sessions[session_id] = {
                        "master_fd": master_fd,
                        "pid": pid,
                        "clients": {ws},
                    }
                current_session_id = session_id

                # Start background reader thread for this session
                t_thread = threading.Thread(
                    target=read_pty_thread,
                    args=(session_id,),
                    daemon=True,
                )
                t_thread.start()

                await send(ws, {"type": "ready"})

            elif t == "attach":
                with sessions_lock:
                    session = sessions.get(session_id)
                if not session:
                    await send(ws, {"type": "error", "message": "Session not found"})
                    continue
                with sessions_lock:
                    sessions[session_id]["clients"].add(ws)
                current_session_id = session_id
                await send(ws, {"type": "ready"})

            elif t == "input":
                with sessions_lock:
                    session = sessions.get(session_id)
                if session:
                    data = msg.get("data", "")
                    try:
                        os.write(session["master_fd"], data.encode("utf-8"))
                    except OSError:
                        pass

            elif t == "resize":
                with sessions_lock:
                    session = sessions.get(session_id)
                if session:
                    cols = int(msg.get("cols", 80))
                    rows = int(msg.get("rows", 24))
                    # Prevent zero or negative sizing during resize events
                    if cols > 0 and rows > 0:
                        set_pty_size(session["master_fd"], cols, rows)

            elif t == "kill":
                destroy_session(session_id)

    except Exception:
        pass
    finally:
        # Remove this websocket from its session on disconnect
        # but keep the PTY alive for reconnect
        if current_session_id:
            with sessions_lock:
                session = sessions.get(current_session_id)
                if session:
                    session["clients"].discard(ws)


# ── Session cleanup ──────────────────────────────────────────────────────────

def destroy_session(session_id: str):
    with sessions_lock:
        session = sessions.pop(session_id, None)
    if not session:
        return
    try:
        os.kill(session["pid"], signal.SIGKILL)
    except ProcessLookupError:
        pass
    try:
        os.close(session["master_fd"])
    except OSError:
        pass


def destroy_all():
    with sessions_lock:
        ids = list(sessions.keys())
    for sid in ids:
        destroy_session(sid)


# ── Entry point ──────────────────────────────────────────────────────────────

async def main():
    global loop
    loop = asyncio.get_running_loop()

    async with serve(handle, HOST, PORT):
        print(f"[terminal-server] Listening on ws://{HOST}:{PORT}", flush=True)
        await asyncio.Future()  # run forever


def shutdown(sig, frame):
    destroy_all()
    sys.exit(0)


signal.signal(signal.SIGTERM, shutdown)
signal.signal(signal.SIGINT, shutdown)

if __name__ == "__main__":
    asyncio.run(main())
